import { createActor, nextId } from './state.js';
import { detectImpossibleInput } from './security.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const dist=(a,b,c,d)=>Math.hypot(a-c,b-d);
function rand(state){ state.rng=((state.rng||1)*1664525+1013904223)>>>0; return state.rng/4294967296; }
export function applyInput(actor,input,dt){ actor.inputSeq=Math.max(actor.inputSeq||0,input.seq||0); actor.yaw=input.yaw??actor.yaw; actor.pitch=input.pitch??actor.pitch; const mx=clamp(input.moveX||0,-1,1), mz=clamp(input.moveZ||0,-1,1); const len=Math.hypot(mx,mz)||1; const speed=(input.sprint?9.5:6.8)*(actor.effects?.speed?1.25:1); const sx=mx/len, sz=mz/len; actor.vx+=(Math.sin(actor.yaw)*sz+Math.cos(actor.yaw)*sx)*speed*dt*8; actor.vz+=(Math.cos(actor.yaw)*sz-Math.sin(actor.yaw)*sx)*speed*dt*8; if(input.dash && actor.cooldowns.dash<=0){ actor.vx+=Math.sin(actor.yaw)*16; actor.vz+=Math.cos(actor.yaw)*16; actor.cooldowns.dash=actor.effects?.doubleDash?.charges?0.2:.9; } }
export function validateAction(actor, action, now=0){ if(action==='throwBomb') return actor.ammo?.some(v=>v>0) && actor.cooldowns.bomb<=0; if(action==='dash') return actor.cooldowns.dash<=0; if(action==='pickup') return actor.cooldowns.pickup<=0; return true; }
export function stepSimulation(state, inputs=[], dt=1/20){ state.tick++; state.events=[]; const byId=new Map([...state.players,...state.bots].map(a=>[a.id,a])); if(state.matchTime<30&&!state.suddenDeath){state.suddenDeath=true; state.events.push({type:'sudden-death'});} for(const input of inputs){ const a=byId.get(input.playerId); if(!a||a.flags.dead) continue; const problems=detectImpossibleInput(a,input,dt); if(problems.length){ state.events.push({type:'invalid-input',playerId:a.id,problems}); if(problems.some(p=>p.includes('frequent'))) continue; } applyInput(a,input,dt); if(input.throwBomb && validateAction(a,'throwBomb')) throwBomb(state,a); }
 for(const a of byId.values()){ a.cooldowns.bomb=Math.max(0,a.cooldowns.bomb-dt*(a.effects?.rapidReload?1.8:1)); a.cooldowns.dash=Math.max(0,a.cooldowns.dash-dt); a.cooldowns.pickup=Math.max(0,a.cooldowns.pickup-dt); tickEffects(a,dt); if(a.respawnAt&&state.stats.duration>=a.respawnAt) respawnActor(state,a); a.x=clamp(a.x+a.vx*dt,-55,55); a.z=clamp(a.z+a.vz*dt,-43,43); a.vx*=Math.pow(.12,dt); a.vz*=Math.pow(.12,dt); }
 updateBombs(state,dt); updatePickups(state,byId); state.matchTime=Math.max(0,state.matchTime-dt); state.stats.duration+=dt; return state; }
function throwBomb(state,a){ const idx=a.ammo.findIndex(v=>v>0); if(idx<0) return; a.ammo[idx]--; a.cooldowns.bomb=.35; a.stats.bombsUsed++; const id=nextId('bomb'); state.bombs.push({id,type:idx,ownerId:a.id,x:a.x+Math.sin(a.yaw),z:a.z+Math.cos(a.yaw),vx:Math.sin(a.yaw)*18,vz:Math.cos(a.yaw)*18,timer:1.1}); state.events.push({type:'bomb-thrown',id,ownerId:a.id}); }
function updateBombs(state,dt){ for(const b of state.bombs){ b.x+=b.vx*dt; b.z+=b.vz*dt; b.timer-=dt; if(b.timer<=0){ b.dead=true; state.events.push({type:'explosion',id:b.id,x:b.x,z:b.z}); for(const a of [...state.players,...state.bots]) if(!a.flags.dead && dist(a.x,a.z,b.x,b.z)<6){ a.hp-=a.flags.shield?18:45; if(a.hp<=0){ a.flags.dead=true; a.stats.deaths++; a.respawnAt=(state.stats.duration||0)+3; const owner=[...state.players,...state.bots].find(x=>x.id===b.ownerId); if(owner&&owner.id!==a.id){ owner.stats.kos++; owner.score=(owner.score||0)+100; state.score[owner.id]=(state.score[owner.id]||0)+100; } state.events.push({type:'ko',victimId:a.id,ownerId:b.ownerId}); } } } } state.bombs=state.bombs.filter(b=>!b.dead); }
function updatePickups(state,byId){ for(const p of state.pickups){ if(p.dead) continue; for(const a of byId.values()) if(!a.flags.dead && validateAction(a,'pickup') && dist(a.x,a.z,p.x,p.z)<1.4){ p.dead=true; applyPickup(a,p); a.cooldowns.pickup=.25; state.events.push({type:'pickup',playerId:a.id,pickupId:p.id,pickupType:p.kind||'ammo'}); break; } } state.pickups=state.pickups.filter(p=>!p.dead); }
function applyPickup(a,p){ if((p.kind||'ammo')==='ammo') a.ammo[p.type]=(a.ammo[p.type]||0)+(p.amount||1); if(p.kind==='speed') addEffect(a,'speed',8); if(p.kind==='shield') addEffect(a,'shield',6); if(p.kind==='doubleDash') addEffect(a,'doubleDash',7); if(p.kind==='rapidReload') addEffect(a,'rapidReload',8); }
function addEffect(a,name,time){ a.effects=a.effects||{}; a.effects[name]=time; if(name==='shield') a.flags.shield=true; }
function tickEffects(a,dt){ if(!a.effects) return; for(const k of Object.keys(a.effects)){ a.effects[k]-=dt; if(a.effects[k]<=0){ delete a.effects[k]; if(k==='shield') a.flags.shield=false; } } }
function respawnActor(state,a){ a.flags.dead=false; a.hp=a.maxHp; a.x=(rand(state)*2-1)*10; a.z=(rand(state)*2-1)*10; a.respawnAt=0; a.ammo[0]=Math.max(a.ammo[0]||0,2); state.events.push({type:'respawn',playerId:a.id}); }
export function addBot(state,data={}){ const bot=createActor('bot',{name:data.name||'BOT',...data}); state.bots.push(bot); return bot; }
